---
title: "Creating Final Dataset"
author: "Alex Furuya"
date: "5/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Library

```{r}
# Loading Library
library(tidyverse)
```

### Data Wrangling

```{r}
# Loading Data
hospice <- read_csv("final.csv") %>%
  mutate(
    PHTYPE = as.factor(PHTYPE),
    READMSS = as.factor(READMSS),
    SEX = as.factor(SEX),
    HISPAN = as.factor(HISPAN),
    RACEAMIN = as.factor(RACEAMIN),
    RACEASIA = as.factor(RACEASIA),
    RACEBLCK = as.factor(RACEBLCK),
    RACEPACI = as.factor(RACEPACI),
    RACEWHT = as.factor(RACEWHT),
    MARSTAT = as.factor(MARSTAT),
    MCARENR = as.factor(MCARENR),
    MCAIDENR = as.factor(MCAIDENR),
    INPATIENT = as.factor(INPATIENT),
    LIVALONE = as.factor(LIVALONE),
    ANYADDIR = as.factor(ANYADDIR),
    ANYHOSDEV = as.factor(ANYHOSDEV),
    ANYSERVC = as.factor(ANYSERVC),
    ANYOTHSVC = as.factor(ANYOTHSVC),
    ANYCOUNSL = as.factor(ANYCOUNSL),
    ANYSRVTYP = as.factor(ANYSRVTYP),
    ANYEMSRV = as.factor(ANYEMSRV),
    PRIPAYOR = as.factor(PRIPAYOR)
  )

# Filtering Out NAs in AVEDLYCH
hospice <- hospice %>%
  filter(!is.na(AVEDLYCH))

# Deselecting Variables with Many NAs
hospice <- hospice %>%
  select(-HOSPICEDAYS, -AGEATINT, -LIVALONE)
```

# Multivariable Regression

```{r}
# Fitting GLM
fit <- glm(AVEDLYCH ~., data = hospice)

# Summarizing Fit
summary(fit)

# Diagnostic Plot
plot(fit)
```

