---
title: "Creating Final Dataset"
author: "Alex Furuya"
date: "5/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Loading Library
library(tidyverse)
library(car)
```

```{r}
# Loading Raw Data
final <- read_tsv("data/unprocessed/28961-0002-Data.tsv")

# Removing Negative Values
final[final < 0] = NA

# Selecting Variables of Interest
final <- final %>%
  select(PHTYPE,
         READMSS,
         AVEDLYCH,
         SEX,
         HISPAN,
         RACEAMIN,
         RACEASIA,
         RACEBLCK,
         RACEPACI,
         RACEWHT,
         MARSTAT,
         MCARENR,
         MCAIDENR,
         INPATIENT,
         CDDX1,
         TOTCDDX,
         TOTPROC,
         TOTALADL,
         COGNFUNC,
         ANYADDIR,
         ANYHOSDEV,
         ANYSERVC,
         ANYOTHSVC,
         ANYCOUNSL,
         ANYSRVTYP,
         ANYEMSRV)

# Filtering Out NAs 
final <- final %>%
  na.omit

# Skimming Off Abnormally High AVEDLYCH
final <- final %>%
  filter(AVEDLYCH < 1000)

# Recoding Primary Diagnosis into Broader Categories

# Extracting First Three Digits of ICD9 Code
digit <- function(x){
 str_extract(x, "^[A-Z0-9]{3}") 
}

final <- final %>%
   mutate(CDDX1 = map(CDDX1, digit))

# Converting Code into Numerical
final <- final %>%
  mutate(CDDX1 = as.numeric(CDDX1))

# Categorizing Code into Broader Categories
final <- final %>%
  mutate(CDDX1 = 
           ifelse(CDDX1 %in% 001:139, "infection",
           ifelse(CDDX1 %in% 140:240, "neoplasms",
           ifelse(CDDX1 %in% 240:279, "endocrine",
           ifelse(CDDX1 %in% 280:289, "blood",
           ifelse(CDDX1 %in% 290:319, "mental",
           ifelse(CDDX1 %in% 320:389, "nerve",
           ifelse(CDDX1 %in% 390:459, "circulatory",
           ifelse(CDDX1 %in% 460:519, "respiratory",
           ifelse(CDDX1 %in% 520:579, "digestive",
           ifelse(CDDX1 %in% 580:629, "genitourinary",
           ifelse(CDDX1 %in% 630:679, "pregnancy",
           ifelse(CDDX1 %in% 680:709, "skin",
           ifelse(CDDX1 %in% 710:739, "musculoskeletal",
           ifelse(CDDX1 %in% 740:759, "congenital",
           ifelse(CDDX1 %in% 760:779, "perinatal",
           ifelse(CDDX1 %in% 780:799, "symptoms",
           ifelse(CDDX1 %in% 800:999, "injury", "other")
           )))))))))))))))))

# One Hot Encoding Factors
final <- final %>%
  mutate(MARSTAT = factor(MARSTAT),
         MCAIDENR = factor(MCAIDENR),
         CDDX1 = factor(CDDX1))

MARSTAT_dum <- as.data.frame(model.matrix(~final$MARSTAT)[,-1])
MCAIDENR_dum <- as.data.frame(model.matrix(~final$MCAIDENR)[,-1])
CDDX1_dum <- as.data.frame(model.matrix(~final$CDDX1)[,-1])

final <- cbind(final, MARSTAT_dum, MCAIDENR_dum, CDDX1_dum)

final <- final %>%
  select(-MARSTAT, -MCAIDENR, -CDDX1)

# Reorganizing Data
final <- final[,c(3, 13, 14, 15, 16, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 17:47)]

# Recoding Data
final[,6] <- recode(final[,6],"2=0")
final[,7] <- recode(final[,7],"2=0")
final[,8] <- recode(final[,8],"2=0")
final[,9] <- recode(final[,9],"2=0")
final[,10] <- recode(final[,10],"2=0")
final[,11] <- recode(final[,11],"2=0")
final[,12] <- recode(final[,12],"2=0")
final[,13] <- recode(final[,13],"2=0")
final[,14] <- recode(final[,14],"2=0")
final[,15] <- recode(final[,15],"2=0")
final[,16] <- recode(final[,16],"2=0")
final[,17] <- recode(final[,17],"2=0")
final[,18] <- recode(final[,18],"2=0")
final[,19] <- recode(final[,19],"2=0")
final[,20] <- recode(final[,20],"2=0")
final[,21] <- recode(final[,21],"2=0")
final[,22] <- recode(final[,22],"2=0")
final[,23] <- recode(final[,23],"2=0")

# Renaming Data Variables
colnames(final)[colnames(final)=="final$MARSTAT2"] <- "MARSTAT2"
colnames(final)[colnames(final)=="final$MARSTAT3"] <- "MARSTAT3"
colnames(final)[colnames(final)=="final$MARSTAT4"] <- "MARSTAT4"
colnames(final)[colnames(final)=="final$MARSTAT5"] <- "MARSTAT5"
colnames(final)[colnames(final)=="final$MARSTAT6"] <- "MARSTAT6"

colnames(final)[colnames(final)=="final$MCAIDENR2"] <- "MCAIDENR2"
colnames(final)[colnames(final)=="final$MCAIDENR3"] <- "MCAIDENR3"

colnames(final)[colnames(final)=="final$CDDX1circulatory"] <- "CDDX1circulatory"
colnames(final)[colnames(final)=="final$CDDX1congenital"] <- "CDDX1congenital"
colnames(final)[colnames(final)=="final$CDDX1digestive"] <- "CDDX1digestive"
colnames(final)[colnames(final)=="final$CDDX1endocrine"] <- "CDDX1endocrine"
colnames(final)[colnames(final)=="final$CDDX1genitourinary"] <- "CDDX1genitourinary"
colnames(final)[colnames(final)=="final$CDDX1infection"] <- "CDDX1infection"
colnames(final)[colnames(final)=="final$CDDX1injury"] <- "CDDX1injury"
colnames(final)[colnames(final)=="final$CDDX1mental"] <- "CDDX1mental"
colnames(final)[colnames(final)=="final$CDDX1musculoskeletal"] <- "CDDX1musculoskeletal"
colnames(final)[colnames(final)=="final$CDDX1neoplasms"] <- "CDDX1neoplasms"
colnames(final)[colnames(final)=="final$CDDX1nerve"] <- "CDDX1nerve"
colnames(final)[colnames(final)=="final$CDDX1other"] <- "CDDX1other"
colnames(final)[colnames(final)=="final$CDDX1perinatal"] <- "CDDX1perinatal"
colnames(final)[colnames(final)=="final$CDDX1pregnancy"] <- "CDDX1pregnancy"
colnames(final)[colnames(final)=="final$CDDX1respiratory"] <- "CDDX1respiratory"
colnames(final)[colnames(final)=="final$CDDX1skin"] <- "CDDX1skin"
colnames(final)[colnames(final)=="final$CDDX1symptoms"] <- "CDDX1symptoms"

# Exporting CSV
write.csv(final, file = "final.csv", row.names = F)
```

